spring:
  thymeleaf:
    cache: false
    enabled: true
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html  
  security:
    oauth2:
      client:
        registration:
           facebook:
              clientId: 6610033279118568
              clientSecret: ddd919fbb89c4a90ef0d61fd30f5c4ad
              accessTokenUri: https://graph.facebook.com/oauth/access_token
              userAuthorizationUri: https://www.facebook.com/dialog/oauth
              tokenName: oauth_token
              authenticationScheme: query
              clientAuthenticationScheme: form
              resource:
                 userInfoUri: https://graph.facebook.com/me

server:
  port: 8080
  

